[DOC_INTEL_SERVICE]
URL="https://[SERVICE].cognitiveservices.azure.com/"
KEY="KEY"

[AI_BLOB_SERVICE]
URL="https://[SERVICE].blob.core.windows.net/"
KEY="KEY"
CONTAINERS = ["KEY"]

[OPENAI_PLATFORM]
URL=""
KEY="KEY"